services:
  split_api:
    build: .
    container_name: split_api
    env_file:
      - .env
    networks:
      - split_network
    depends_on:
      - split_db

  split_db:
    image: postgres:alpine
    restart: no
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - split_db_data:/var/lib/postgresql
    networks:
      - split_network

volumes:
  split_db_data:

networks:
  split_network:
