"""Each Participant belongs to only one BillItem

Revision ID: 0dd1885194b2
Revises: b3f19038b583
Create Date: 2026-04-29 12:53:01.800405

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dd1885194b2"
down_revision: Union[str, Sequence[str], None] = "b3f19038b583"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bill_participant_bill_item_id"), table_name="bill_participant"
    )
    op.drop_index(
        op.f("ix_bill_participant_participant_id"), table_name="bill_participant"
    )
    op.drop_table("bill_participant")
    op.add_column("participant", sa.Column("bill_item_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_participant_bill_item_id"),
        "participant",
        ["bill_item_id"],
        unique=False,
    )
    op.create_foreign_key(None, "participant", "bill_item", ["bill_item_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.drop_index(op.f("ix_participant_bill_item_id"), table_name="participant")
    op.drop_column("participant", "bill_item_id")
    op.create_table(
        "bill_participant",
        sa.Column("participant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("bill_item_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_item_id"],
            ["bill_item.id"],
            name=op.f("bill_participant_bill_item_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participant.id"],
            name=op.f("bill_participant_participant_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("bill_participant_pkey")),
    )
    op.create_index(
        op.f("ix_bill_participant_participant_id"),
        "bill_participant",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bill_participant_bill_item_id"),
        "bill_participant",
        ["bill_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###
